name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        working-directory: ./backend
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t sort-geek:latest .

      - name: Save Docker image as tar
        run: docker save -o sort-geek.tar sort-geek:latest

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "sort-geek.tar"
          target: "/home/ubuntu/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker load -i /home/ubuntu/sort-geek.tar
            sudo docker compose down --volumes --remove-orphans
            sudo -E docker compose up -d --remove-orphans
